apiVersion : apps/v1
kind: Deployment
metadata:
  name: "flaskcluster-61ed"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "flaskcluster-61ed"
  template:
    metadata:
      labels:
        app: "flaskcluster-61ed"
    spec:
      containers:
        - name: "flaskcluster-61ed"
          image: "flasklab1.azurecr.io/flaskcluster"
          ports:
          - containerPort: 80