apiVersion: v1
kind: Service
metadata:
    name: "flasklab2-a454"
    labels:
        app: "flasklab2-a454"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "flasklab2-a454"