apiVersion: v1
kind: Service
metadata:
    name: "flaskcluster-61ed"
    labels:
        app: "flaskcluster-61ed"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "flaskcluster-61ed"